姓名:建立
在……之上:
workflow_dispatch:
输入:
package_name:
描述:"com.tencent.tmgp.pubgmhd："
必需的:正确

工作:
建立:
run-on:ubuntu-最新
步骤:
-uses:操作/签出@v3
-uses:操作/设置-java@v3
和……一起:
分布:temurin
java版:11
缓存:Gradle
-跑:|
chmod+x./gradlew
SED-i的/moduleDescription="/moduleDescription="(${{github。event.inputs.package_name}})/g'module.gradle
SED-i"s/com.game.packagename/${{github.event.inputs.package_name}}/g"模块/src/main/cpp/Game.h
./gradlew：模块：assemblyRelease
-uses:操作/上载工件@v3
和……一起:
姓名:zygisk-il2cppdumper
路径:out/magisk_module_release/
